[package]
name = "minivm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kvm-bindings = "0.4"
kvm-ioctls = "0.9"
mmarinus = "0.2"
